coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "*.test.js"
  - "**/*.test.js"
  - "coverage/**/*"
  - "node_modules/**/*"
